export const snippets = [
  'const add = (a, b) => a + b;',
  'const double = arr => arr.map(x => x * 2);',
  'const sum = arr => arr.reduce((a, b) => a + b, 0);',
  'const unique = arr => [...new Set(arr)];',
  'const clamp = (n, min, max) => Math.min(Math.max(n, min), max);',
  'const last = arr => arr[arr.length - 1];',
  'const flatten = arr => arr.flat();',
  'const sleep = ms => new Promise(r => setTimeout(r, ms));',
  'const range = n => Array.from({ length: n }, (_, i) => i);',
  'const isEmpty = val => val == null || val.length === 0;',
  'def add(a, b): return a + b',
  'def double(lst): return [x * 2 for x in lst]',
  'def flatten(lst): return [x for sub in lst for x in sub]',
  'def unique(lst): return list(dict.fromkeys(lst))',
  'def clamp(n, lo, hi): return max(lo, min(n, hi))',
  '.center { display: flex; align-items: center; justify-content: center; }',
  '.truncate { overflow: hidden; white-space: nowrap; text-overflow: ellipsis; }',
  '* { box-sizing: border-box; margin: 0; padding: 0; }',
  'body { font-family: system-ui, sans-serif; line-height: 1.5; }',
  'const toggle = (arr, x) => arr.includes(x) ? arr.filter(i => i !== x) : [...arr, x];',
]
